#!/usr/bin/env bash

set -euo pipefail

# Fedora 44 p11-kit trust store needs to be re-extracted after base stage removes /var/run
update-ca-trust

dnf config-manager addrepo --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
dnf config-manager setopt nvidia-container-toolkit.enabled=0
dnf config-manager setopt nvidia-container-toolkit.gpgcheck=1
dnf -y install --enablerepo='nvidia-container-toolkit' nvidia-container-toolkit

dnf -y copr enable eyecantcu/supergfxctl
dnf -y copr enable pgaskin/looking-glass-client

grep -vE '^#' /usr/share/nuclear/packages-added-nvidia | xargs dnf -y install --best --allowerasing
